### PR TITLE
Make catching the rejected API call optional

### LINKED ISSUE #741: Attempting to create a property with a name that already exists results in an unhandled promise error
**Describe the bug**
Attempting to create a property with a name that already exists results in an unhandled promise error

**To Reproduce**
1. Create a property with a name that already exists

**Expected behavior**
No errors

**Screenshots**
Screen Shot 2021-11-14 at 8 35 39 AM

### PR DESCRIPTION
**Pull request by NickSchimek**
Fixes #741

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? no
Any special requirements to test? dont think so

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed

### CODE REVIEW

File: src/App.jsx [hunk 1]
```diff
@@ -201,6 +201,11 @@ export class App extends React.Component {
       Toast(toastMessages.error ?? error.message, "error");
       return Promise.reject(error);
     })
+    // since we already display the erorr message. The caller does not need to catch the returned Promise.
```
Comment (Chris-Boe) [inline src/App.jsx:204]: Should we just replace the `return Promise.reject(error)` above with `return false`?

I thought about doing something like this but wanted the error to be available to the caller for additional catching, but I think this is fine

**Review by Chris-Boe — APPROVED** [review]

File: src/App.jsx (hunk 1 above)
Comment (NickSchimek) [reply src/App.jsx:204]: > Should we just replace the return Promise.reject(error) above with return false?

I thought about this too, and almost did that exact thing.

But then I came to the same conclusion as you. I think it will be useful to have the error available to the caller.
