### PR TITLE
Fix scoping on notes

### LINKED ISSUE #841: Edit and Delete Note APIs are missing
**Describe the bug**
Either the frontend is hitting the wrong API or the API is missing in the backend. The frontend is currently sending Note Edits to:
PATCH /api/tickets/{ticketId}/notes/{noteId}
and it's coming back with a  500

It's also sending Delete requests to:
DELETE /api/tickets/136/notes/2
and it's coming back with a 500

**To Reproduce**
1. Go to a ticket
2. Add a note
3. Attempt to edit note and save changes
5. Attempt to delete note and save changes
6. See error

**Expected behavior**

**Screenshots**
Edit:
image

Delete:
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by NickSchimek**
Pass in ticket.notes to the notes policy scope.

Fix scope when its a property manager. A Property manager can only update/destroy their own note.

Fixes #841

### Any helpful knowledge/context for the reviewer?
Is a `yarn install` necessary?
Any special requirements to test? 

### Please make sure you've attempted to meet the following coding standards
- [x] There aren't any unnecessary commits or files changed
- [x] Code has been tested and does not produce errors
- [x] There isn't any unnecessary commented-out code

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

File: app/policies/note_policy.rb [hunk 1]
```diff
@@ -9,7 +9,7 @@ def resolve
       if user.staff_level?
         scope.all
       else
-        user.properties.property_managers
+        scope.where(user: user)
```
Comment (NickSchimek) [inline app/policies/note_policy.rb:12]: I don't remember if a property manager is allowed to edit/destroy any note as long as it was created by one of their co-managers.

If that is the case then this should be `scope.where(user: user.properties.property_managers)`

**Review by Chris-Boe — APPROVED** [review]

File: app/policies/note_policy.rb (hunk 1 above)
Comment (Chris-Boe) [reply app/policies/note_policy.rb:12]: I think this is fine for now, we can come back to it if we need to
