### PR TITLE
Issue658 Fix role API calls

### LINKED ISSUE #658: Remove backend call to get list of roles
**Purpose**
Remove the backend call to request a list of roles. This information is readily available in the frontend code and an ajax request is not needed here.

The frontend has a RoleEnum that can be used to get a list of roles. The following ajax requests should be replaced with a method call to the FE RoleEnum.

The following needs to be updated:

https://github.com/codeforpdx/dwellingly-app/blob/432888bcac2ef5362719ed668bd11f00732ef63d/src/views/requestAccess/requestAccess.jsx#L71

Screen Shot 2021-07-07 at 9 30 44 AM

### PR DESCRIPTION
**Pull request by Chris-Boe**
### What issue is this solving?
Closes #658 

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? n
Any special requirements to test? n

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

File: src/views/requestAccess/requestAccess.jsx [hunk 1]
```diff
@@ -68,20 +68,11 @@ export const RequestAccess = (props) => {
...
-      })
-      .catch((error) => {
-        Toast(error.message, "error");
-        console.log(error);
-      });
+    let roles = [];
+    for(var key in RoleEnum) {
+      roles.push(key);
+    }
+    setSelectionOptions(roles);
```
Comment (NickSchimek) [inline src/views/requestAccess/requestAccess.jsx]: Would this work too?

```suggestion
    setSelectionOptions(Object.keys(RoleEnum));
```

File: src/views/Manager/index.jsx [hunk 2]
```diff
@@ -145,7 +145,7 @@ const Manager = () => {
             <div className="section-container">
               <h2 className="secondary-title">PROPERTIES</h2>
               <div className="manager__properties__container">
-                {managerData.properties.map((property) => (
+                {managerData.properties?.map((property) => (
```
Comment (NickSchimek) [inline src/views/Manager/index.jsx:148]: What does this `?` mark do?

**Review by NickSchimek — DISMISSED** [review]
Thanks for doing this Chris! I have a couple questions, otherwise it looks good! Thanks!

File: src/views/Manager/index.jsx (hunk 2 above)
Comment (Chris-Boe) [reply src/views/Manager/index.jsx:148]: It's an optional chain marker, meaning if managerData.properties is "nullish", it will short circuit and will just return undefined instead of throwing an error. Since this is in the render method, it falls back to rendering nothing

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

File: src/views/requestAccess/requestAccess.jsx (hunk 1 above)
Comment (Chris-Boe) [reply src/views/requestAccess/requestAccess.jsx]: Much better! I think I was way too tired when I was writing this fix 😂

File: src/views/Manager/index.jsx (hunk 2 above)
Comment (NickSchimek) [reply src/views/Manager/index.jsx:148]: Nice! I didn't know Javascript had that. Ruby has something similar called safe navigation using the `&` character.

**Review by NickSchimek — APPROVED** [review]
