### PR TITLE
Make 'add property manager' optional in AddProperty component

### LINKED ISSUE #745: Unable to search and assign property manager when creating a property via the create manager page
**Describe the bug**
Assigning a property manager on the Add Property Modal within the the add Property Manager page does not allow the user to filter the results, and does not allow the user to scroll through the list of results.

**To Reproduce**

Prior data needed:
There must be a lot of property managers in the system, enough to fill your screen height with results.

1. Go to `/add/manager` endpoint
2. Click on `Create New Property`
3. Click in the Search Property Managers search panel
4. Notice it does not allow to search and immediately displays the entire list without the ability to scroll.

**Expected behavior**

**Screenshots**
Screen Shot 2021-11-15 at 3 03 20 PM

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Chrome
 - Version 94

# Follow up Question

Should the assign property manager even be visible within this context?

If your creating a manager, and find yourself needing to create a new property, then I would assume you don't need to add existing managers to this property. If that's the case they can probably create the property first or add after creating the current PM?

I checked the figma docs, but I couldn't find the page where we add a property manager, and it has this modal open. 

Screen Shot 2021-11-15 at 3 13 15 PM

### PR DESCRIPTION
**Pull request by yunnie**
### What issue is this solving?
Please connect this Pull Request to the issue it is resolving by using the controls on the right side of this PR. 

Closes #745

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? No
Any special requirements to test? No

### Please make sure you've attempted to meet the following coding standards
- [ x] Code builds successfully
- [ x] Code has been tested and does not produce errors
- [ x] Code is readable and formatted
- [ x] There isn't any unnecessary commented-out code
- [ x] There aren't any unnecessary commits or files changed

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

File: app/javascript/components/src/views/AddTenant/index.jsx [hunk 1]
```diff
@@ -447,6 +447,7 @@ const AddTenant = () => {
                 showPageTitle={false}
                 handleCancel={closePropertyModal}
                 afterCreate={closeAndSetProperty}
+                showAssignPropManagers={true}
```
Comment (Chris-Boe) [inline app/javascript/components/src/views/AddTenant/index.jsx]: Setting this to true for the modal to show the property manager selection still breaks the functionality when the list is too long. Should we just switch it to false if we don't need it here as well?

**Review by Chris-Boe — CHANGES_REQUESTED** [review]

File: app/javascript/components/src/views/AddTenant/index.jsx (hunk 1 above)
Comment (yunnie) [reply app/javascript/components/src/views/AddTenant/index.jsx]: The width of the Property Manager search field has a fixed with in `AddProperty` component. Is there a way to adjust the size of the `SearchPanel` so that it takes in the appropriate size automatically? Or we could make the width an input.

Comment (yunnie) [reply app/javascript/components/src/views/AddTenant/index.jsx]: I added a size option to the `SearchPanel` in the `AddProperty` component. So the property manager search now fits in the modal.

Comment (Chris-Boe) [reply app/javascript/components/src/views/AddTenant/index.jsx]: The width control helps but it's the vertical size of the dropdown being off the page that's the issue:
image

Comment (Chris-Boe) [reply app/javascript/components/src/views/AddTenant/index.jsx]: I think we can limit the size across the board and make it scrollable to fix it

**Review by Chris-Boe — CHANGES_REQUESTED** [review]

File: app/javascript/components/src/views/AddTenant/index.jsx (hunk 1 above)
Comment (yunnie) [reply app/javascript/components/src/views/AddTenant/index.jsx]: I ended up using your original suggestion and removed the "Assign Property Manager". I tried setting a max height, but no matter what height I used, it always ended up pushing the "save" and "cancel" buttons off the screen.

**Review by NickSchimek — APPROVED** [review]
